name: 🧾 Code Checks

on: [merge_group, pull_request]

env:
  CI: true

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests pass
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run test:ci
        working-directory: ./tests

  build:
    runs-on: ubuntu-latest
    name: Panda Preset successfully builds
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run build
        working-directory: ./packages/panda-preset

  # build:
  #   runs-on: ubuntu-latest
  #   name: Ganglion successfully builds
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: pnpm/action-setup@v3
  #       with:
  #         version: 8
  #     - uses: actions/setup-node@v4
  #       with:
  #         cache: 'pnpm'

  #     - run: pnpm install
  #     - run: pnpm run build
  #       working-directory: ./packages/ganglion
