name: 🧾 Code Checks

on: [merge_group, pull_request]

env:
  CI: true

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests pass
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'

      - run: pnpm install
      - run: pnpm run test:ci
        working-directory: ./tests

  solid-tests:
    runs-on: ubuntu-latest
    name: Tests pass
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'

      - run: pnpm install
      - run: pnpm run test:ci
        working-directory: ./tests

  react-build:
    runs-on: ubuntu-latest
    name: React successfully builds
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'

      - run: pnpm install
      - run: pnpm run build
        working-directory: ./packages/react

  solid-build:
    runs-on: ubuntu-latest
    name: Solid successfully builds
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'

      - run: pnpm install
      - run: pnpm run build
        working-directory: ./packages/solid
