name: 🚀 Publish Stable Version

on: [merge_group, pull_request]
# on:
#   release:
#     types:
#       - published

env:
  CI: true
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  npm-publish-react:
    runs-on: ubuntu-latest
    name: Build & Publish React to NPM
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'

      - run: pnpm install
      - run: pnpm build && pnpm publish --access public --no-git-checks
        working-directory: ./packages/react

  npm-publish-styled-system:
    runs-on: ubuntu-latest
    name: Build & Publish Styled-System to NPM
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'

      - run: pnpm install
      - run: pnpm publish --access public --no-git-checks
        working-directory: ./packages/styled-system

  jsr-publish-preset:
    runs-on: ubuntu-latest
    name: Publish Preset Latest Version to JSR
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm dlx jsr publish --allow-dirty
        working-directory: ./packages/panda-preset
