name: 🚀 Publish Next Version

on: [merge_group, pull_request]
# on:
#   push:
#     branches:
#       - main

env:
  CI: true
  AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish-npm-next:
    runs-on: ubuntu-latest
    name: Build & Publish Next Version to NPM
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - run: echo "//registry.npmjs.org/:_authToken=$AUTH_TOKEN" >> .npmrc
      - run: pnpm install
      - run: pnpm run publish --next --commit ${{ github.sha }}
        working-directory: ./configs

  create-jsr-next-versions:
    runs-on: ubuntu-latest
    name: Update JSR Next Versions
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.4

      - run: pnpm install
      - run: pnpm run publish:jsr --next --commit ${{ github.sha }}
        working-directory: ./configs

  # There is a bug in JSR publishing the errors with next versions
  # So we are creating a new job for each public package
  publish-preset-jsr-next:
    runs-on: ubuntu-latest
    name: Publish Preset Next Version to JSR
    needs: create-jsr-next-versions
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.4

      - run: pnpm dlx jsr publish --allow-dirty
        working-directory: ./packages/panda-preset

  publish-icons-jsr-next:
    runs-on: ubuntu-latest
    name: Publish Icons Next Version to JSR
    needs: create-jsr-next-versions
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.4

      - run: pnpm dlx jsr publish --allow-dirty
        working-directory: ./packages/icons
