name: 🚀 Publish Next Version

on: [merge_group, pull_request]
# on:
#   push:
#     branches:
#       - main

env:
  CI: true
  AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish-npm-next:
    runs-on: ubuntu-latest
    name: Build & Publish Next Version to NPM
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.3
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'

      - run: echo "//registry.npmjs.org/:_authToken=$AUTH_TOKEN" >> .npmrc
      - run: pnpm install
      - run: pnpm run publish --next --commit ${{ github.sha }}
        working-directory: ./configs
