name: 🚀 Publish Stable Version

on:
  release:
    types:
      - published

env:
  CI: true
  AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish-npm-stable:
    runs-on: ubuntu-latest
    name: Build & Publish Stable Version to NPM
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - run: echo "//registry.npmjs.org/:_authToken=$AUTH_TOKEN" >> .npmrc
      - run: pnpm install
      - run: pnpm run publish --stable
        working-directory: ./configs

  # There is a bug in JSR publishing the errors with next versions
  # So we are creating a new job for each public package
  publish-preset-jsr-next:
    runs-on: ubuntu-latest
    name: Publish Preset Next Version to JSR
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run publish:jsr --stable
        working-directory: ./configs

      - run: pnpm dlx jsr publish --allow-dirty
        working-directory: ./packages/panda-preset

  publish-icons-jsr-next:
    runs-on: ubuntu-latest
    name: Publish Icons Next Version to JSR
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run publish:jsr --stable
        working-directory: ./configs

      - run: pnpm dlx jsr publish --allow-dirty
        working-directory: ./packages/icons
