name: 🚀 Publish Next Version

on: [merge_group, pull_request]
# on:
#   push:
#     branches:
#       - main

env:
  CI: true
  AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  npm-publish-react-next:
    runs-on: ubuntu-latest
    name: Build & Publish Next Version to NPM
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'

      - run: pnpm install
      - run: pnpm build
        working-directory: ./packages/react
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/react
